#!/bin/bash
set -e
PROJECT="/var/folders/_9/w0f85fv10494qtdm7v8p5k_80000gn/T/opencode/detox"
echo "=== DETØX AAB Builder ==="
echo "Project: $PROJECT"
cd "$PROJECT"
echo ""
echo "1) Installing deps..."
npm install --legacy-peer-deps
echo ""
echo "2) Prebuild (generates android/)"
npx expo prebuild --clean --platform android || echo "prebuild needs EAS, skipping locally"
echo ""
echo "3) EAS Build → AAB"
echo "   Run: eas build --platform android --profile production"
echo "   Or for local .aab (requires Android SDK):"
echo "   npx eas build --platform android --profile production --local"
echo ""
echo "=== AdMob Setup ==="
echo "Replace in app.json: react-native-google-mobile-ads androidAppId"
echo "Replace in src/ads/adMob.ts: banner/interstitial/rewarded IDs"
echo "Then: npx expo prebuild --clean && eas build"
echo ""
echo "=== Play Store ==="
echo "Upload: build-*.aab to Play Console → Production → Internal testing"
echo "Data Safety: No data collected, Ads yes, Encryption yes"
echo "Content rating: Everyone, Contains ads"
